---
title: 
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
    code_folding: hide
---

# MTA Ridership Mobility Trends 2019 and 2020

### Description 

Visualization of mobility changes and differences between 2019 and 2019 before conducting statistical analyses. 

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
library(readr)
library(broom)
library(dbplyr)
library(viridis)
library(reshape2)
library(plotly)
library(lubridate)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))

mta_data = read_csv (file = "./data/MTA_recent_ridership_data_20201123_0.csv",
                     col_types = cols(
                       date = col_date(format = "%mm/%dd/%yy"),
                       `Subways: % Change From 2019 Equivalent Day` = col_number(),
                       `Buses: % Change From 2019 Equivalent Day` = col_number(),
                       `Bridges and Tunnels: % Change From 2019 Equivalent Day` = col_number()
                       ) #only changed the formats of important variables 
) %>%
  janitor::clean_names()
skimr::skim(mta_data)
mta_data =
  mta_data %>%
  subset(select = -c(lirr_total_estimated_ridership, lirr_percent_change_from_2019_monthly_weekday_saturday_sunday_average, metro_north_total_estimated_ridership, metro_north_percent_change_from_2019_monthly_weekday_saturday_sunday_average, access_a_ride_total_scheduled_trips, access_a_ride_percent_change_from_2019_monthly_weekday_saturday_sunday_average, bridges_and_tunnels_total_traffic, bridges_and_tunnels_percent_change_from_2019_equivalent_day))
#exclude data for lirr, metronorth, access-a-ride, bridges & tunnel
```


``` {r, include=FALSE}
mta_data = mta_data %>%
  mutate( 
    'subway_2019' = subways_total_estimated_ridership/(1+(subways_percent_change_from_2019_equivalent_day/100)),
    'bus_2019'=
      buses_total_estimated_ridership/(1+(buses_percent_change_from_2019_equivalent_day/100))
    ) %>%
  rename(
    "subway_2020" = subways_total_estimated_ridership,
    "subway_pct_change" = subways_percent_change_from_2019_equivalent_day,
    "bus_2020" = buses_total_estimated_ridership,
    "bus_pct_change" = buses_percent_change_from_2019_equivalent_day
    )
```


```{r, include=FALSE}
#change date to date format and order by date
mta_data =
  mta_data %>%
  mutate(
    date= as.Date(date,format = "%m/%d")) %>%
  arrange(date)
#create a text_label label
text_label =
  mta_data %>%
  mutate(text_label = str_c("percent change from 2019 to 2020: ", subway_pct_change)) %>%
  select(date, text_label)

#graph for subway 
#pivoting
plot_subway = 
  mta_data %>%
  select(subway_2019, subway_2020, date) %>%
  melt(., id.vars = "date") %>%
#merge based on month 
  merge(text_label, by = "date") %>%
  #plotting
  plot_ly(
    x = ~date, y = ~value, type = "scatter", mode = "markers",
    color = ~variable, text = ~text_label) %>%
  layout (
    title = "Subway Ridership Trends 2019 - 2020",
    xaxis = list(title ="Month/Day", tickformat = "%m/%d"), #drop year
    yaxis = list(title="Ridership"))  %>%
  add_lines(x =as.Date("2020-03-01"), line = list(dash="dot", color = 'red', width=0.5, opacity = 0.5),name = 'First case on 3/1') %>%
  add_lines(x =as.Date("2020-04-07"), line = list(dash="dot", color = 'red', width=0.5, alpha = 0.5),name = '100K cases in NYC on 04/07') %>%
  add_lines(x =as.Date("2020-05-26"), line = list(dash="dot", color = 'red', width=0.5, alpha = 0.5),name = '200K cases in NYC on 05/26')
#graph for bus

#pivoting
plot_bus = 
  mta_data %>%
  select(bus_2019,bus_2020,date) %>%
  melt(., id.vars = "date") %>% 
#merge based on month 
  merge(text_label, by = "date") %>%
#plotting
  plot_ly(
    x = ~date, y = ~value, type = "scatter", mode = "markers",
    color = ~variable, text = ~text_label) %>%
  layout (
    title = "Bus Ridership Trends 2019 - 2020",
    xaxis = list(title ="Month/Day", tickformat = "%m/%d"),
    yaxis = list(title="Ridership")) %>%
  add_lines(x =as.Date("2020-03-01"), line = list(dash="dot", color = 'red', width=0.5, opacity = 0.5),name = 'First case on 3/1') %>%
  add_lines(x =as.Date("2020-04-07"), line = list(dash="dot", color = 'red', width=0.5, alpha = 0.5),name = '100K cases in NYC on 04/07') %>%
  add_lines(x =as.Date("2020-05-26"), line = list(dash="dot", color = 'red', width=0.5, alpha = 0.5),name = '200K cases in NYC on 05/26')

```

### Subway Ridership Trends 2019 and 2020

```{r, message=FALSE}
#ggplot for subway
plot_subway_2 = 
  mta_data %>%
  select(subway_2019, subway_2020, date) %>%
  melt(., id.vars = "date") %>%
  ggplot(aes(x=date, y=value, color=variable)) +
  geom_point(alpha=0.5) +
  geom_smooth(se = FALSE)  +
  geom_vline(xintercept=as.Date("2020-03-01"), linetype="dotted", color = 'red')+
  geom_vline(xintercept=as.Date("2020-04-07"), linetype="dotted", color = 'red')+
  geom_vline(xintercept=as.Date("2020-05-26"), linetype="dotted", color = 'red')+
  geom_text(x=as.Date("2020-03-01"), y=6100000, label ="First case", angle=90, vjust = 1.2, size=3,color='black') +
  geom_text(x=as.Date("2020-04-07"), y=6100000, label ='100K cases', angle=90, vjust = 1.2, size=3,color='black')+
  geom_text(x=as.Date("2020-05-26"), y=6100000, label ='200K cases', angle=90, vjust = 1.2, size=3,color='black')
ggplotly(plot_subway_2)
```

### Bus Ridership Trends 2019 and 2020 

```{r, message=FALSE}
#ggplot for bus
plot_bus_2 = 
  mta_data %>%
  select(bus_2020, bus_2019,date) %>%
  melt(., id.vars = "date") %>% 
  ggplot(aes(x=date, y=value, color=variable)) +
  geom_point(alpha=0.5) +
  geom_smooth(se = FALSE) +  
  geom_vline(xintercept=as.Date("2020-03-01"), linetype="dotted", color = 'red')+
  geom_vline(xintercept=as.Date("2020-04-07"), linetype="dotted", color = 'red')+
  geom_vline(xintercept=as.Date("2020-05-26"), linetype="dotted", color = 'red')+
  geom_text(x=as.Date("2020-03-01"), y=2400000, label ="First case", angle=90, vjust = 1.2, size=3,color='black') +
  geom_text(x=as.Date("2020-04-07"), y=2400000, label ='100K cases', angle=90, vjust = 1.2, size=3,color='black')+
  geom_text(x=as.Date("2020-05-26"), y=2400000, label ='200K cases', angle=90, vjust = 1.2, size=3,color='black')
ggplotly(plot_bus_2)

#see the two graphs together:
plot_bus
plot_subway
(plot_bus_2+plot_subway_2)
```

